debate-timer/debate-timer-be

- .github/workflows/Auto_Issue_Setting.yml
> [FIX] 이슈 템플릿 작성 시, Assignees 자동 할당

- build.gradle
- src/main/java/com/debatetimer/swagger/annotation/ErrorCode400.java
- src/main/java/com/debatetimer/swagger/annotation/ErrorCode401.java
- src/main/java/com/debatetimer/swagger/annotation/ErrorCode404.java
- src/main/java/com/debatetimer/swagger/annotation/ErrorCode500.java
- src/main/java/com/debatetimer/swagger/config/SwaggerConfig.java
- src/main/resources/application.yml
closed #14 
Swagger 관련 환경 설정 완료하였습니다.
앞으로 문서화 관련 step과 Swagger를 처음 써보는 팀원을 위한 Swagger 코드 설명을[ 문서화](https://www.notion.so/Swagger-1591550c60cf80c3a642e186a6ab23e6)해놓았습니다.
+) 에러 객체로 ProblemDetail을 반환토록 해놓았는데 괜찮은지 여쭈어요
> [CHORE] Swagger 문서화 환경 세팅

- .github/workflows/PR_Comment_Notification.yml
> [REFACTOR] 알림 워크플로우 타이틀 수정

- .github/workflows/PR_Comment_Notification.yml
closed: #27 
- 더 좋은 방법, 개선할 점 있으면 알려주셈
- 지금 secret에 저장된 값을 가져와서 사용함
- github nickname을 discordID로 바꾸는 방식으로 진행
- 이거 develop에 머지 되야 테스트 가능함
- 정상 작동하는 거 확인 : https://github.com/leegwichan/discord-webhook
> [CHORE] /noti 기능에 멘션 추가

- src/test/java/com/debatetimer/BaseControllerTest.java
- src/test/java/com/debatetimer/BaseRepositoryTest.java
- src/test/java/com/debatetimer/BaseServiceTest.java
- src/test/java/com/debatetimer/DataBaseCleaner.java
closed #23 
추가로 넣어야 할 세팅 있으면 말해주세요~
> [TEST] BaseXXXTest 환경 세팅하기

- src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
- src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
- src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
- src/test/java/com/debatetimer/service/BaseServiceTest.java
- src/test/java/com/debatetimer/service/member/MemberServiceTest.java
- src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
closed #51 
- 리뷰 해줘 (10초 컷 예상)
> [TEST] BaseTest 파일 패키지 옮기기

- src/main/java/com/debatetimer/dto/member/TableResponse.java
- src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
> [FIX] 멤버 테이블 조회 요청 수정

- .github/workflows/PR_Comment_Notification.yml
closed #55 
- embeds 에는 PR, Issue 작성자 정보를 띄우도록 함
- 작동하지 않던 PR Review Comment 제거
- 궁금할 것 같은 내용이나 의논이 필요한 내용은 코멘트로 남겨 놓을테니, 의견주세요.
> [CHORE] Discord 알림 embeds 개선

- .github/workflows/PR_Comment_Notification.yml
> [CHORE] PR 리뷰 작성 시, 알림이 안가는 문제 해결

- .github/workflows/Prod_CD.yml
- .github/workflows/Prod_CI.yml
- scripts/prod/replace-new-version.sh
- src/main/resources/application-prod.yml
closed #59 
- prod 용 환경을 dev와 똑같이 분리해놓았습니다.
- test를 통해 ec2 내 어플리케이션 동작 및 cd 파이프라인 정상동작을 확인하였습니다.
- pem key 및 계정 정보는 노션페이지 > 계정에서 확인가능합니다.
- secret 파일은 노션페이지 > GIT_SECRET 탭에서 확인 가능합니다.
- 추후 db migration을 어떻게 할지도 논의해봐야 할 것 같아요. (현재는 ddl-auto : validate 로 설정함)
> [CHORE] prod 환경 분리

- src/main/java/com/debatetimer/repository/member/MemberRepository.java
- src/main/java/com/debatetimer/service/member/MemberService.java
- src/test/java/com/debatetimer/service/member/MemberServiceTest.java
closed #69 
- 이거 비토가 구현한 OAuth 로직 들어오면 사라질 파트라서 대충 짜고 테스트도 대충 함
> [FIX] 임시 로그인 API 수정

- src/main/java/com/debatetimer/service/member/MemberService.java
> [RELEASE] 백엔드 버전 v1.0.1 배포

- src/main/java/com/debatetimer/config/CorsConfig.java
closed #65
- CORS 허용 메서드에 PUT 추가
- 단순 작업이므로 by-pass로 진행
> [FEAT] CORS 설정

- src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/request/TableInfoCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
- src/main/resources/application-local.yml
- src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
- src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
- src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxesTest.java
- src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
- src/test/java/com/debatetimer/service/member/MemberServiceTest.java
- src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> [FEAT] 반환값에 종소리 flag값 추가

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> [FIX] yml파일 수정

- src/main/resources/application-dev.yml
> chore: db 방언 직접 지정

- .gitignore
- src/main/java/com/debatetimer/client/OAuthProperties.java
- src/main/java/com/debatetimer/dto/member/MemberCreateRequest.java
- src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
- src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
> [FIX] redirect_url_mismatch 문제 해결

- src/main/java/com/debatetimer/config/CorsConfig.java
- src/main/java/com/debatetimer/controller/member/MemberController.java
- src/main/java/com/debatetimer/controller/tool/cookie/CookieManager.java
- src/main/java/com/debatetimer/controller/tool/cookie/CookieProvider.java
- src/test/java/com/debatetimer/controller/BaseDocumentTest.java
- src/test/java/com/debatetimer/controller/GlobalControllerTest.java
- src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
- src/test/java/com/debatetimer/fixture/CookieGenerator.java
> [FIX] 클라이언트에 헤더 및 쿠키 공개 설정 fix 기능 수정

- build.gradle
closed #78 
- 로컬로 Swagger 한 번 열어보는 것을 추천!
> [DOCS] Swagger host 변경

- src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
closed #95 
- 간단한 반영 내용이라 크게 없습니다.
> [FEAT] 단건 조회에 토론 형식을 같이 반환하도록 수정

- src/main/java/com/debatetimer/config/CorsConfig.java
- src/main/java/com/debatetimer/config/WebConfig.java
- src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
- src/main/java/com/debatetimer/controller/tool/export/ExcelExport.java
- src/main/java/com/debatetimer/controller/tool/export/ExcelExportInterceptor.java
- src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
- src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExcelExporter.java
- src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExportMessageResolver.java
closed #81 
- 엑셀 첨부 header 설정을 담당하는 인터셉터 위치 고민 : 현재는 controller/tool/export 아래에 위치
- WebConfig에서 의존성 주입으로 인터셉터를 설정하도록 했는데 그냥 new ExcelExportInterceptor() 직접 생성하는 것은 어떠한지 궁금합(컴포턴트로 선언할 필요가 없을 것 같아서)
> [FEAT] 의회식 토론  EXPORT Api 구현

- src/main/java/com/debatetimer/client/OAuthProperties.java
- src/main/java/com/debatetimer/config/CorsConfig.java
- src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProperties.java
- src/main/java/com/debatetimer/exception/custom/DTClientErrorException.java
- src/main/java/com/debatetimer/exception/custom/DTErrorResponseException.java
- src/main/java/com/debatetimer/exception/custom/DTInitializationException.java
- src/main/java/com/debatetimer/exception/custom/DTServerErrorException.java
- src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
- src/main/java/com/debatetimer/exception/errorcode/InitializationErrorCode.java
- src/main/java/com/debatetimer/exception/errorcode/ResponseErrorCode.java
- src/main/java/com/debatetimer/exception/errorcode/ServerErrorCode.java
- src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
- src/test/java/com/debatetimer/client/OAuthPropertiesTest.java
- src/test/java/com/debatetimer/config/CorsConfigTest.java
- src/test/java/com/debatetimer/controller/tool/jwt/JwtTokenPropertiesTest.java
- src/test/resources/application.yml
closed #97 
- 궁금한 점이 있다면 커밋 메시지를 볼 것
> [REFACTOR] 스프링 시작 시 발생하는 예외 설정

- build.gradle
- src/main/java/com/debatetimer/DebateTimerApplication.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V1__initialize_table.sql
- src/main/resources/db/migration/V2__add_time_based_table.sql
- src/test/java/com/debatetimer/DatabaseSchemaManagerTest.java
- src/test/java/com/debatetimer/DebateTimerApplicationTest.java
- src/test/resources/application-flyway.yml
- src/test/resources/application.yml
closed #101 
- Flyway 설명회는 2월 27일 BE 회의에 진행하도록 하겠습니다.
> [CHORE] DB 형상 관리 도구 도입

- src/main/java/com/debatetimer/domain/BaseTimeEntity.java
closed #112 
자세한 이슈내용은 이슈(#112) 참고
> [FIX] time auditing이 되지 않는 문제 개선

- src/main/java/com/debatetimer/domain/DebateTable.java
- src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
- src/main/java/com/debatetimer/domain/timebased/TimeBasedTable.java
- src/main/java/com/debatetimer/dto/member/TableResponse.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableInfoCreateRequest.java
- src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
- src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableInfoCreateRequest.java
- src/main/resources/db/migration/V4__drop_duration_column.sql
- src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
- src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
- src/test/java/com/debatetimer/domain/DebateTableTest.java
- src/test/java/com/debatetimer/domain/TimeBoxesTest.java
- src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
- src/test/java/com/debatetimer/fixture/TimeBasedTableGenerator.java
> [REFACTOR] 멤버 테이블 조회에서 소요시간 대신 주제 반환

- src/main/java/com/debatetimer/domain/DebateTimeBox.java
- src/main/java/com/debatetimer/domain/customize/BoxType.java
- src/main/java/com/debatetimer/domain/customize/CustomizeBoxType.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
- src/main/java/com/debatetimer/dto/member/TableType.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableInfoCreateRequest.java
- src/main/resources/db/migration/V5__add_customize_table.sql
- src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
- src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
> [FEAT] 사용자 지정 테이블 Entity 구현

- src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
- src/main/java/com/debatetimer/controller/timebased/TimeBasedController.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
- src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
- src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepository.java
- src/main/java/com/debatetimer/repository/timebased/TimeBasedTimeBoxRepository.java
- src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
- src/main/java/com/debatetimer/service/timebased/TimeBasedService.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
- src/test/java/com/debatetimer/controller/timebased/TimeBasedControllerTest.java
- src/test/java/com/debatetimer/controller/timebased/TimeBasedDocumentTest.java
- src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
- src/test/java/com/debatetimer/service/timebased/TimeBasedServiceTest.java
closed #115 
- 시간 총량제 테이블 수정 API는 PATCH -> PUT 으로 바꾸었습니다.
- 추가적으로 눈에 보이는 리팩토링 실시했습니다. 보기 힘드시면 커밋 단위로 리뷰해주세요!
> [FEAT] Debate API 구현

- src/main/java/com/debatetimer/domain/DebateTable.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
- src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
- src/test/java/com/debatetimer/domain/DebateTableTest.java
- src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
> [REFACTOR] 테이블 명, 팀 이름 검증 수정

- src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
- src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
- src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
- src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTableResponse.java
- src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTimeBoxResponse.java
- src/test/java/com/debatetimer/controller/customize/CustomizeControllerTest.java
- src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
- src/test/java/com/debatetimer/controller/timebased/TimeBasedControllerTest.java
- src/test/java/com/debatetimer/fixture/CustomizeTimeBoxGenerator.java
- src/test/java/com/debatetimer/fixture/ParliamentaryTimeBoxGenerator.java
- src/test/java/com/debatetimer/fixture/TimeBasedTimeBoxGenerator.java
> [HOTFIX] NullException처리

- src/main/java/com/debatetimer/domain/DebateTimeBox.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
- src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
- src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
- src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
> [FEAT] 발언자 길이 및 발언유형 길이 검증

- src/main/java/com/debatetimer/domain/DebateTable.java
- src/main/java/com/debatetimer/domain/DebateTimeBox.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
- src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
- src/main/java/com/debatetimer/dto/customize/request/CustomizeTableCreateRequest.java
- src/main/java/com/debatetimer/dto/customize/request/CustomizeTimeBoxCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
- src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTimeBoxCreateRequest.java
- src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
- src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTimeBoxCreateRequest.java
- src/test/java/com/debatetimer/domain/DebateTableTest.java
- src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
- src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
- src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
closed #140 
- 테스트 필요하다 vs Valid 테스트하는 거므로 필요치 않다
> [REFACTOR] Blank 검증을 DTO에서 일관성있게 수행

- src/main/java/com/debatetimer/dto/member/TableResponses.java
- src/main/java/com/debatetimer/service/member/MemberService.java
- src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
- src/test/java/com/debatetimer/service/member/MemberServiceTest.java
> [REFACTOR] 회원 테이블 조회 시 커스텀 테이블 포함

- src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
- src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
- src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
closed #133 
비토식 회의 참여(비동기)으로 리뷰 부탁드립니다.
> [REFACTOR] speakerNumber parseInt에 따른 NPE 문제 개선

- src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
> [REFACTOR] time_based 일 때 time을 null로 반환

- build.gradle
- scripts/dev/replace-new-version.sh
- scripts/prod/replace-new-version.sh
- src/main/resources/application-monitor.yml
- src/test/java/com/debatetimer/domain/TimeBoxesTest.java
closed #127 
- 일단 DEV 모니터링 붙였습니다.
- QA 하는 환경에서 서버 테스트 해보려 하는데 괜찮나요? 무리인가요?
> [CHORE] 모니터링 설정 추가

- scripts/dev/replace-new-version.sh
- scripts/prod/replace-new-version.sh
#157 
일단 배포 이후 정상작동을 확인해야 해서, 머지하도록 하겠습니다.
> [CHORE] Datadog APM 설정

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/logging/log4j2-dev.yml
- src/main/resources/logging/log4j2-prod.yml
#163
- 1차적으로 서버에 로그를 남기는 작업 진행
- 이후, Datadog과 연결하는 작업 진행 예정
> [CHORE] DataDog을 통한 로그 수집

- src/main/resources/application.yml
- src/test/java/com/debatetimer/controller/RestDocumentationRequest.java
- src/test/java/com/debatetimer/controller/customize/CustomizeDocumentTest.java
- src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
closed #165 
- description 이 추가된 Swagger 문서
> [DOCS] Swagger를 통해 추가 설명 제시

- src/main/java/com/debatetimer/repository/customize/CustomizeTableRepository.java
- src/main/java/com/debatetimer/service/customize/CustomizeService.java
- src/test/java/com/debatetimer/controller/customize/CustomizeDocumentTest.java
- src/test/java/com/debatetimer/repository/customize/CustomizeTableRepositoryTest.java
- src/test/java/com/debatetimer/service/customize/CustomizeServiceTest.java
closed #167
- 쓰기 락이 필요한 조회와, 쓰기 락이 필요없는 조회가 둘 다 필요하다보니 코드가 더러워졌어요. 개선 방안 제시해주시면 바로 반영하겠습니다~
- 동시성 해결 방안은 아래 코멘트 참고해주세요!
- 의회식 타입은 지워지니까 작업하지 않았습니다~
> [FIX] '토론 테이블 변경 API' 동시성 문제
